// Pure functions around the official Tibia experience formula.
//
// exp(level) = round((50/3) * (level^3 - 6*level^2 + 17*level - 12))
//
// This formula is exact for every level Tibia has ever shipped, so we use it
// directly instead of looking values up in a static table. That also means
// levels beyond 3500 "just work" without needing a bigger table.
//
// `src/data/tibia_experience_table.json` still ships in the repo (generated by
// scripts/generate-experience-table.mjs) as the canonical 1-3500 reference
// dataset, and is used in a couple of places to cross-check this formula.

/** Highest level Tibia has officially published experience values for. Used for input validation, not as a hard cap on calculations. */
export const MAX_KNOWN_LEVEL = 3500;

export function experienceForLevel(level: number): number {
  if (!Number.isInteger(level) || level < 1) {
    throw new Error(`Invalid level: ${level}. Level must be an integer >= 1.`);
  }
  return Math.round((50 / 3) * (level ** 3 - 6 * level ** 2 + 17 * level - 12));
}

/**
 * Finds the highest level whose required experience is <= the given experience.
 * Uses exponential search to find an upper bound, then binary search — keeps
 * this O(log level) and correct for arbitrarily large experience values.
 */
export function levelForExperience(experience: number): number {
  if (!Number.isFinite(experience) || experience < 0) {
    throw new Error(`Invalid experience: ${experience}. Must be a non-negative number.`);
  }

  let low = 1;
  let high = 1;
  while (experienceForLevel(high) <= experience) {
    high *= 2;
  }

  while (low < high) {
    const mid = low + Math.ceil((high - low) / 2);
    if (experienceForLevel(mid) <= experience) {
      low = mid;
    } else {
      high = mid - 1;
    }
  }

  return low;
}
